name: workflow.yml
on: push
#  push:
#    branches:
#      - main


jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: backend
        run: |
          echo "building backend"
          pwd

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23.4
        run: pwd
      - run: go mod tidy
      - run: go build *.go


