name: workflow.yml
on:
  push:
    branches:
      - main


jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: backend
        run: |
          echo "building backend"

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: frontend
        run: |
          echo "building frontend"
